color0 #111417
color1 #ffb4ab
color2 #92cdfd
color3 #b3c9de
color4 #e5b6f7
color5 #92cdfd
color6 #b3c9de
color7 #e1e2e6
color8 #8b9199
color9 #ffb4ab
color10 #92cdfd
color11 #b3c9de
color12 #e5b6f7
color13 #92cdfd
color14 #b3c9de
color15 #e1e2e6

cursor                #e1e2e6
cursor_text_color     #111417
background            #111417
foreground            #e1e2e6
selection_foreground  #c0c7cf
selection_background  #41474e
active_border_color   #92cdfd
inactive_border_color #41474e
url_color             #92cdfd

active_tab_foreground   #003450
active_tab_background   #92cdfd
inactive_tab_foreground #c0c7cf
inactive_tab_background #41474e
cursor_trail_color      #c0c7cf
